# Base configs
baseurl: "https://mpvanderschelling.github.io/feestboek"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Martin zoekt kamer in Rotterdam!"
subtitle: "See the world through my eyes!"
author: "Martin van der Schelling"
header:
 title: "Martin"
 subtitle: "zoekt kamer in Rotterdam!"
footer:
 name: "Hoi hoi!"
 bio: "Dit is een kleine biografie en een fotocollage om mij te helpen een kamer te zoeken in Rotterdam!<br><br>Hopelijk werkt html ook hier."
 github: ""
web_design: "AJ"
social_urls:
  linkedin: "https://www.linkedin.com/in/mpvanderschelling/"
  github: "https://github.com/mpvanderschelling"
