# Base configs
baseurl: "https://mpvanderschelling.github.io/feestboek"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Martin van der Schelling"
subtitle: "See the world through my eyes!"
author: "Martin van der Schelling"
header:
 title: "Martin"
 subtitle: "zoekt kamer in Rotterdam"
footer:
 name: "Hoi hoi!"
 bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  linkedin: "https://www.linkedin.com/in/mpvanderschelling/"
  github: "https://github.com/mpvanderschelling"
