# Base configs
baseurl: "https://mpvanderschelling.github.io/feestboek"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Martin van der Schelling"
subtitle: "See the world through my eyes!"
author: "Martin van der Schelling"
header:
 title: "Martin"
 subtitle: "van der Schelling"
footer:
 name: "Hi!"
 bio: "Hi! I am Martin, 28 years old, originally from Breda (the Netherlands), and I'm a PhD candidate from Delft University of Technology! I am involved in music and have been playing the piano for several years in my cover band <a href=\"https://www.deklittenband.nl\">De Klittenband</a>. Besides music, I also regularly participate in sports like field-hockey and soccer. Additionally, I go snowboarding annually in the French Alps. I also frequently visit my club Feyenoord to watch soccer games, supporting the most beautiful club in the Netherlands :)."
 github: ""
web_design: "AJ"
social_urls:
  linkedin: "https://www.linkedin.com/in/mpvanderschelling/"
  github: "https://github.com/mpvanderschelling"


